version: "3.9"

services:

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - /var/log/marcobrico:/logs
      - ./promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
  db:
    image: postgres:16-alpine
    container_name: marcobrico-db
    environment:
      POSTGRES_USER: marcobrico
      POSTGRES_PASSWORD: marcobrico123
      POSTGRES_DB: marcobrico
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - marcobrico-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: marcobrico-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@marcobrico.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - marcobrico-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

#  api:
#    build: .
#    container_name: marcobrico-api
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/marcobrico
#      SPRING_DATASOURCE_USERNAME: marcobrico
#      SPRING_DATASOURCE_PASSWORD: marcobrico123
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_JPA_SHOW_SQL: "true"
#      JWT_SECRET: secret-key-to-change
#    depends_on:
#      - db
#    networks:
#      - marcobrico-network
  marcobrico:
    build:
      context: .
      target: build
volumes:
  db-data:
  pgadmin-data:
  grafana-data:

networks:
  marcobrico-network:

