server:
  port: 8080
  servlet:
    context-path: /api

spring:
  devtools:
    restart:
      enabled: true
      trigger-file: .reloadtrigger
  application:
    name: marcobrico-management

  datasource:
    url: jdbc:postgresql://localhost:5432/marcobrico
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 2xVq8F9pN3kL7mZ1wR4tY6uI0oP5aS8dG1hJ3kM2nB9=
  expiration: 86400000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

