server:
  port: 8080
  servlet:
    context-path: /api

spring:
  devtools:
    restart:
      enabled: true
      trigger-file: .reloadtrigger
  application:
    name: marcobrico-management

  datasource:
    url: jdbc:postgresql://localhost:5432/marcobrico
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    root: INFO
    org.springframework.web: INFO
#    org.hibernate.SQL: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

