apiVersion: apps/v1
kind: Deployment
metadata:
  name: marcobrico-db
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marcobrico-db
  template:
    metadata:
      labels:
        app: marcobrico-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: marcobrico-db-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}