name: Marcobrico CI
run-name: CI validation 🧪

on:
  pull_request:
    branches: [ develop, master ]
  push:
    branches: [ develop, master ]

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build & Run Tests
        run: mvn clean verify

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: marcobrico-jar
          path: target/*.jar